services:
  loki:
    image: grafana/loki:3.7.2
    ports:
      - "3101:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./local-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    networks:
      - loki-net

networks:
  loki-net:
    driver: bridge
