version: '3'

services:
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins-data:/var/jenkins_home"
  
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"

volumes:
  jenkins-data: