pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }
    
    environment {
        SONAR_TOKEN = credentials('sonar-token')
        // GITHUB_CREDENTIALS = credentials('github-token')
    }
    
    
    stages {
         stage('Checkout Code') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        branches: [[name: '*/master']],
                        userRemoteConfigs: [[url: 'https://github.com/alex-carvalho/sandbox']]]
                    )
                }
            }
        }

        stage('Build') {
            steps {
                dir("samples/java/spring-web-3-j21"){
                    sh './gradlew clean build -x test'
                }
                
            }
        }
        
        stage('Test') {
            steps {
                dir("samples/java/spring-web-3-j21"){
                    sh './gradlew test'
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir("samples/java/spring-web-3-j21"){
                    sh './gradlew sonar -Dsonar.token=$SONAR_TOKEN'
                }
            }
        }

        stage('Upload artfact') {
            steps {
                dir("samples/java/spring-web-3-j21"){
                    sh 'aws s3 cp build/libs/spring-web-3-j21-0.0.1-SNAPSHOT.jar s3://my-artifacts/app.jar'
                }
            }
        }

         stage('Terraform Init') {
            steps {
                dir("devops/challenges/jenkins-spring-ec2/terraform-files") {
                    sh 'tflocal init'
                }
            }
        }
        
        stage('Terraform Plan') {
            steps {
                dir("devops/challenges/jenkins-spring-ec2/terraform-files") {
                    sh 'tflocal plan -input=false -no-color -out=plan.tfplan'
                }
            }
        }

        // stage('Terraform Aprove?') {
        //     options {
        //         timeout( time: 1, unit: 'MINUTES' )
        //     }  
        //     steps {
        //         script {
        //             input(
        //                 message: 'Proceed with above Terraform Plan??',
        //                 ok: 'Proceed'
        //             )
        //         }
        //     }
        // }
        
        stage('Terraform Apply') {
            steps {
                dir("devops/challenges/jenkins-spring-ec2/terraform-files") {
                    sh 'tflocal apply -auto-approve -input=false -no-color plan.tfplan'
                }
            }
        }
    }
}