pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }
    
    environment {
        DOCKER_REGISTRY = 'ghcr.io/alex-carvalho/sandbox'
    }
    
    stages {
         stage('Checkout Code') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        branches: [[name: '*/master']],
                        userRemoteConfigs: [[url: 'https://github.com/alex-carvalho/sandbox']]]
                    )
                }
            }
        }

        stage('Build java') {
            steps {
                dir("samples/java/spring-web-3-j21"){   
                    sh 'gradle clean build -x test --no-daemon'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir("samples/java/spring-web-3-j21"){
                    sh 'gradle test --no-daemon'
                }
            }
        }

        stage('Login to GHCR') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'ghcr-creds', usernameVariable: 'GHCR_USER', passwordVariable: 'GHCR_TOKEN')]) {
                    sh 'echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin'
                }
            }
        }

        stage('Docker build') {
            steps {
                dir("samples/java/spring-web-3-j21"){
                    sh "docker build -t $DOCKER_REGISTRY/spring-web-3-j21:$BUILD_NUMBER ."
                }
            }
        }

        stage('Docker push') {
            steps {
                dir("samples/java/spring-web-3-j21"){
                    sh "docker push $DOCKER_REGISTRY/spring-web-3-j21:$BUILD_NUMBER "
                }
            }
        }

        stage('Build Helm Chart') {
            steps {
                dir("devops/challenges/opentofu-k8s-deploy/helm/app") {
                    sh 'helm lint .'
                    sh 'helm package .'
                }
            }
        }

        stage('Deploy Helm Chart') {
            steps {
                dir("devops/challenges/opentofu-k8s-deploy/helm/app") {
                    sh "helm upgrade --install java-app --set image.tag=$BUILD_NUMBER ."
                }
            }
        }
    }
}