apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd # needs to go to argocd namespace where ArgoCD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/alex-carvalho/sandbox.git
    targetRevision: HEAD
    path: devops/gitops/argocd/examples/guestbook/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: apps