apiVersion: v1
kind: Service
metadata:
  name: spring-web-3-j21
  labels:
    app: spring-web-3-j21
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: spring-web-3-j21 