services:
  java-app:
    image: ghcr.io/alex-carvalho/sandbox/spring-web-3-j21:latest
    environment:
      - LOGSTASH_URL=logstash:5044
    ports:
      - "8080:8080"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    ports:
      - "5601:5601"
    networks:
      - app-network
    depends_on:
      - elasticsearch
    volumes:
    - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  app-network:
    driver: bridge