apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-web-3-j21
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alex-carvalho/sandbox.git
    targetRevision: HEAD
    path: devops/challenges/jenkins-spring-argocd/helm/spring-web-3-j21
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true