apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: my-app-error-rate
  namespace: {{ .Release.Namespace }}
spec:
  metrics:
    - name: app-health
      interval: {{ .Values.analysis.interval }}
      failureLimit: {{ .Values.analysis.failureLimit }}
      successCondition: result[0] > 0.99
      provider:
        prometheus:
          address: {{ .Values.analysis.prometheusAddress }}
          query: |
            sum(rate(http_requests_total{job="my-app",result="success"}[1m]))
            /
            sum(rate(http_requests_total{job="my-app"}[1m]))