apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: my-app-error-rate
  namespace: {{ .Release.Namespace }}
spec:
  metrics:
    - name: app-health
      interval: 15s
      failureLimit: 3
      successCondition: result[0] > 0.99
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{job="my-app-canary",result="success"}[1m]))
            /
            sum(rate(http_requests_total{job="my-app-canary"}[1m]))
