apiVersion: v1
kind: Service
metadata:
  name: canary-app-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: canary-app
spec:
  selector:
    app: canary-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: canary-app-stable-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: canary-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: canary-app-canary-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: canary-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 8080
      targetPort: 8080
