services:
  pulsar:
    image: apachepulsar/pulsar:4.2.0
    container_name: pulsar
    command: >
      bash -c "bin/pulsar standalone"
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g
    volumes:
      - pulsar_data:/pulsar/data
      - pulsar_conf:/pulsar/conf
    restart: unless-stopped
    networks:
      - pulsar-net

  dekaf:
    image: visortelle/dekaf:1.1.0
    restart: always
    environment:
      DEKAF_PULSAR_WEB_URL: "http://pulsar:8080"
      DEKAF_PULSAR_BROKER_URL: "pulsar://pulsar:6650"
    volumes:
      - dekaf-library:/dekaf/data/library
    ports:
      - "8090:8090"
    networks:
      - pulsar-net

volumes:
  pulsar_data:
  pulsar_conf:
  dekaf-library:

networks:
  pulsar-net:
    driver: bridge
